server:
  port: 8080

spring:
  application:
    name: jasper
  datasource:
    url: jdbc:postgresql://localhost:5432/installment
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update